# Generated by Django 4.2.20 on 2025-05-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="raffle",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="raffle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="raffles.raffle",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raffle",
            name="banner",
            field=models.ImageField(upload_to="banner"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("FR", "Libre"), ("SET", "Apartado"), ("PD", "Pagado")],
                default="FR",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="raffles.user",
            ),
        ),
    ]
