# Generated by Django 4.2.20 on 2025-05-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0002_raffle_end_date_raffle_start_date_ticket_raffle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
