# Generated by Django 4.2.20 on 2025-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0003_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
