# Generated by Django 4.2.20 on 2025-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('free', 'Libre'), ('set', 'Apartado'), ('paid', 'Pagado')], default='free', max_length=4),
        ),
    ]
