# Generated by Django 4.2.20 on 2025-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0006_rename_user_client_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='tickets_amount',
            field=models.IntegerField(default=100),
        ),
    ]
