# Generated by Django 4.2.20 on 2025-05-13 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0007_raffle_tickets_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='banner',
            field=models.ImageField(upload_to='banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 40, 10, 519968, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 40, 19, 764581, tzinfo=datetime.timezone.utc), verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffle',
            name='ticket_price',
            field=models.FloatField(verbose_name='Precio del ticket'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='tickets_amount',
            field=models.IntegerField(default=100, help_text='Cantidad de tickets a crear. Al menos 1', verbose_name='Cantidad de tickets'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(verbose_name='Número de ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles.raffle', verbose_name='Rifa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('free', 'Libre'), ('set', 'Apartado'), ('paid', 'Pagado')], default='free', max_length=4, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raffles.client', verbose_name='Cliente'),
        ),
    ]
