# Generated by Django 4.2.20 on 2025-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_alter_client_city_alter_client_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Formato: 1234567890 o +34123456789', max_length=15, verbose_name='Teléfono'),
        ),
    ]
