# Generated by Django 4.2.20 on 2025-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='client',
        ),
    ]
