# Generated by Django 4.2.20 on 2025-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0010_rename_user_ticket_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="description",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Descripción"
            ),
            preserve_default=False,
        ),
    ]
