# Generated by Django 4.2.20 on 2025-05-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0011_raffle_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
