# Generated by Django 4.2.20 on 2025-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0012_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raffle",
            name="ticket_price",
            field=models.IntegerField(verbose_name="Precio del ticket"),
        ),
    ]
