# Generated by Django 4.2.20 on 2025-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0013_alter_raffle_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
